project_id = "tkbsjtgrumhvwlxkmojg"

[functions.chat]
verify_jwt = false

[functions.extract-instagram]
verify_jwt = false

[functions.run-automation]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false

[functions.scrape-research-link]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.fetch-beehiiv-metrics]
verify_jwt = false

[functions.scrape-social-metrics]
verify_jwt = false

[functions.reverse-engineer]
verify_jwt = false

[functions.extract-knowledge]
verify_jwt = false

[functions.extract-youtube]
verify_jwt = false

[functions.analyze-research]
verify_jwt = false

[functions.transcribe-images]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.grok-search]
verify_jwt = false

